#!/usr/bin/env bash
set -uxa

if [[ $3 = bathy && $# -eq 3 ]]; then # make new bathy dump look like old bathy dump and cat with really old bathys

  rm -f bathy.ibm 031.ibm newbathy
 
  TANK=$DCOMROOT
  $DUMPJB $1 $2 bathy   >/dev/null 2>&1     # old bathy
  $DUMPJB $1 $2 031 006 >/dev/null 2>&1     # new bathy
  unset FORT20 FORT21 FORT50; rm -rf fort.*
  ln -sf 031.ibm   fort.20
  ln -sf newbathy  fort.50
  $BATYDUMP >/dev/null 2>&1

  cat newbathy >> bathy.ibm

  echo
  ls -l 031.ibm
  ls -l newbathy 
  ls -l bathy.ibm
  echo

elif [[ $3 = tesac && $# -eq 3 && ${GODAS:-YES} = YES ]]; then # combine argo floats with tesac data

  export DUPC=OFF

  # make argo dump look like tesacs and cat with other tesacs

  rm -f tesac.ibm tesac.org argomods

  $DUMPJB $1 $2 tesac   >/dev/null 2>&1     # tesac
  $DUMPJB $1 $2 031 005 >/dev/null 2>&1     # argos

  unset FORT20 FORT21 FORT50; rm -rf fort.*
  ln -sf 031.ibm   fort.20
  ln -sf argomods  fort.50
  $ARGODUMP >/dev/null 2>&1

  [[ -s tesac.ibm ]] && cp  tesac.ibm tesac.org
  [[ -s argomods  ]] && cat argomods >> tesac.ibm

  echo
  ls -l tesac.org 
  ls -l 031.ibm
  ls -l argomods 
  ls -l tesac.ibm
  echo

elif [[ $3 = dbuoy && $# -eq 3  && ${GODAS:-YES} = YES ]]; then

  # dump marine subtypes 002 and 103 into dbuoy collective    

  $DUMPJB $1 $2 001 103 >/dev/null 2>&1  

  mv 001.ibm dbuoy.ibm            

else
  $DUMPJB $*
fi



